.TH PSAXTAB 1

.SH NAME
psaxtab - maintain psaxtabs for individual users.

.SH SYNOPSIS
psaxtab [-u user] file
psaxtab [-u user] [-l | -r | -e] [-i]

.SH DESCRIPTION
TODO:write things here.

.SH OPTIONS
TODO: write things here.

.SH FILES
/etc/psax.allow

/etc/psax.deny

.SH SEE ALSO
psaxtab(5), psax(8)
