.TH PSAX 8

.SH NAME
psax - daemon to support persistent search folders

.SH SYNOPSIS
psax [-p]

.SH DESCRIPTION
psax should be started from /etc/rc.d/init.d or /etc/init.d

TODO:write things here.

.SH OPTIONS
-p     Permissive mode, psax will accept any psaxtab even if it is assigned to a user who did not last modify it.

.SH SEE ALSO
psaxtab(1), psaxtab(5)
